# Generated by Django 5.0.7 on 2024-09-23 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("negocio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="negocio",
            name="direccion",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="negocio",
            name="email",
            field=models.EmailField(
                max_length=254, validators=[django.core.validators.EmailValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="negocio",
            name="horario",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="negocio",
            name="imagen",
            field=models.ImageField(upload_to="negocios/images/"),
        ),
        migrations.AlterField(
            model_name="negocio",
            name="nombre",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="negocio",
            name="telefono",
            field=models.CharField(max_length=20),
        ),
    ]
